# Generated by Django 6.0.3 on 2026-05-06 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unidad",
                    models.CharField(
                        blank=True,
                        help_text="Si se asigna, el usuario solo verá encuestas de esta unidad.",
                        max_length=100,
                        null=True,
                        verbose_name="Unidad restringida",
                    ),
                ),
                (
                    "sucursal",
                    models.CharField(
                        blank=True,
                        help_text="Si se asigna, el usuario solo verá encuestas de esta sucursal.",
                        max_length=100,
                        null=True,
                        verbose_name="Sucursal restringida",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil de Usuario",
                "verbose_name_plural": "Perfiles de Usuario",
            },
        ),
    ]
