"""
Django settings for HorizonZero project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = Path(__file__).resolve().parent.parent.parent
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-$h5e)&^!w@tnucqrnxm5s)j2dse96dvy!7@uki6=*ztrcipvlu'
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.getenv("CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]



# Application definition

DJANGO_APPS = [
    # "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django.contrib.humanize',
]

THIRD_PARTY_APPS = [
     "django_tables2",
]

LOCAL_APPS = [
    
    "apps.core.apps.CoreConfig",
    "apps.usuarios.apps.UsuariosConfig",
    "apps.dashboard.apps.DashboardConfig",
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'apps.core.middleware.FriendlyNotFoundMiddleware',
    'apps.core.middleware.ExcelDownloadFilenameMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'apps.usuarios.middleware_jwt.JWTAuthMiddleware', #nuevo
    'apps.usuarios.middleware.ForcedLogoutMiddleware',
    # 'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "apps.usuarios.middleware.LoginRequiredMiddleware",
  
]

ROOT_URLCONF = 'HorizonZero.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "HorizonZero.wsgi.application"
ASGI_APPLICATION = "HorizonZero.asgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "mssql",
#         "NAME":     os.getenv("DB_NAME"),       # encuestas_db
#         "USER":     os.getenv("DB_USER"),       # encuestas_desa
#         "PASSWORD": os.getenv("DB_PASSWORD"),
#         "HOST":     os.getenv("DB_HOST"),       # SQLWD-VSRV3
#         "PORT":     os.getenv("DB_PORT", "1433"),
#         "OPTIONS": {
#             "driver": os.getenv("DB_DRIVER", "ODBC Driver 17 for SQL Server"),
#             "trust_server_certificate": os.getenv("DB_TRUST_SERVER_CERTIFICATE", "yes"),
#         },
#     },
# }
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.dummy",
    }
}

# SILENCED_SYSTEM_CHECKS = ["django_db_warnings"]

SESSION_ENGINE = "django.contrib.sessions.backends.cache"

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_API_LDAP_URL = os.getenv("AUTH_API_LDAP_URL", "")
# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-cr'

TIME_ZONE = 'America/Costa_Rica'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Cuando creemos el Custom User, lo activamos
# AUTH_USER_MODEL = "usuarios.User"

LOGIN_URL = "/usuarios/login/"
LOGIN_REDIRECT_URL = "/dashboard/"
LOGOUT_REDIRECT_URL = "/usuarios/login/"

# Auth LDAP
AUTH_API_LDAP_URL = os.environ.get("AUTH_API_LDAP_URL", "")


#===========================================================#
# Variables de entorno para el envío de correos
# EMAIL_BACKEND    = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST       = os.getenv('EMAIL_HOST', 'smtp.office365.com')
# EMAIL_PORT       = int(os.getenv('EMAIL_PORT', 25))
# EMAIL_HOST_USER  = os.getenv('EMAIL_HOST_USER', '')
# EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
# EMAIL_USE_TLS    = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
# DEFAULT_FROM_EMAIL = os.getenv('EMAIL_FROM', '')
# DETRACTOR_EMAIL_DESTINO = os.getenv('DETRACTOR_EMAIL_DESTINO', '')
EMAIL_HOST          = os.getenv("EMAIL_HOST")
EMAIL_PORT          = int(os.getenv("EMAIL_PORT", 25))
EMAIL_HOST_USER     = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS       = os.getenv("EMAIL_USE_TLS", "False") == "True"
EMAIL_FROM          = os.getenv("EMAIL_FROM", "horizonzero_noreply@cajadeande.fi.cr")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "horizonzero_noreply@cajadeande.fi.cr")
EMAIL_USE_SSL       = os.getenv("EMAIL_USE_SSL", "False") == "True"
# DETRACTOR_EMAIL_DESTINO = os.getenv('DETRACTOR_EMAIL_DESTINO', '')
EMAIL_TIMEOUT = 30 
#===========================================================#

# VARIABLES PARA ENVIO DE CORREOS A JEFATURAS POR DETRACTORES
def parse_emails(env_key):
    """Convierte 'a@x.com,b@x.com' en ['a@x.com', 'b@x.com']"""
    raw = os.getenv(env_key, "")
    return [e.strip() for e in raw.split(",") if e.strip()]

DETRACTOR_EMAIL_SAT          = parse_emails("DETRACTOR_EMAIL_SAT")
DETRACTOR_EMAIL_OD           = parse_emails("DETRACTOR_EMAIL_OD")
DETRACTOR_EMAIL_WEB          = parse_emails("DETRACTOR_EMAIL_WEB")
DETRACTOR_EMAIL_WA_AGENTE    = parse_emails("DETRACTOR_EMAIL_WA_AGENTE")
DETRACTOR_EMAIL_WA_SIN_AGENTE = parse_emails("DETRACTOR_EMAIL_WA_SIN_AGENTE")

#============================================================================#



# Seguridad de sesiones
SESSION_COOKIE_HTTPONLY = True      # JS no puede leer la cookie
SESSION_COOKIE_SAMESITE = "Lax"     # Protección CSRF básica
SESSION_COOKIE_AGE = 360 * 60       # 6 horas (igual que C# SessionTimeout=360)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True   # Renueva timeout con cada request
# Sesiones en base de datos (requerido para detección de duplicados real)
# SESSION_ENGINE = "django.contrib.sessions.backends.db"
# CSRF
CSRF_COOKIE_HTTPONLY = False        # Django lo necesita en JS


# SESSION_COOKIE_SECURE = True        # Solo HTTPS (en producción)
# CSRF_COOKIE_SECURE = True           # Solo HTTPS


AUTHENTICATION_BACKENDS = [
    "apps.usuarios.backends.LDAPAuthBackend",
    "django.contrib.auth.backends.ModelBackend",
]


# DATABASE_ROUTERS = ['apps.dashboard.routers.EncuestasDBRouter']

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "horizonzero-login-attempts",
    }
}

# Intentos máximos en Login para dar avisos.
LOGIN_MAX_ATTEMPTS = int(os.getenv("LOGIN_MAX_ATTEMPTS", "5"))
LOGIN_BLOCK_MINUTES = int(os.getenv("LOGIN_BLOCK_MINUTES", "1"))

API_INTERNAL_KEY = os.getenv("API_INTERNAL_KEY", "")
# ── API interna ───────────────────────────────────────────────────
USE_API      = os.getenv("USE_API", "False") == "True"
API_URL      = os.getenv("API_URL", "")
API_USER     = os.getenv("API_USER", "")
API_PASSWORD = os.getenv("API_PASSWORD", "")
