"""
Django settings for HorizonZero project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = Path(__file__).resolve().parent.parent.parent
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-$h5e)&^!w@tnucqrnxm5s)j2dse96dvy!7@uki6=*ztrcipvlu'
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-change-me")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")



# Application definition

DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django.contrib.humanize',
]

THIRD_PARTY_APPS = [
     "django_tables2",
]

LOCAL_APPS = [
    "apps.core.apps.CoreConfig",
    "apps.usuarios.apps.UsuariosConfig",
    "apps.dashboard.apps.DashboardConfig",
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "apps.usuarios.middleware.LoginRequiredMiddleware",
    'apps.core.middleware.LimpiarCachePermisosMiddleware',
]

ROOT_URLCONF = 'HorizonZero.urls'

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "HorizonZero.wsgi.application"
ASGI_APPLICATION = "HorizonZero.asgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "mssql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT", "1433"),
        "OPTIONS": {
            "driver": os.getenv("DB_DRIVER", "ODBC Driver 17 for SQL Server"),
            "trust_server_certificate": os.getenv("DB_TRUST_SERVER_CERTIFICATE", "yes"),
        },
    },
    # Data base de reportes: Esto debe cambiarse y modificar por la de producción con usuario y contraseña. Tambien el server correcto
    "reportes_db": {
        "ENGINE": "mssql",
        "NAME": os.getenv("REPORTS_DB_NAME"),
        "HOST": os.getenv("REPORTS_DB_HOST"),
        "PORT": os.getenv("REPORTS_DB_PORT", "1433"),
        "OPTIONS": {
            # "driver": "ODBC Driver 17 for SQL Server",
            "trusted_connection": "yes",        # ← Windows Authentication
            # "trust_server_certificate": "yes",  # ← igual que tu imagen
            "driver": os.getenv("DB_DRIVER", "ODBC Driver 17 for SQL Server"),
            "trust_server_certificate": os.getenv("DB_TRUST_SERVER_CERTIFICATE", "yes"),
        },
    },

}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_API_LDAP_URL = os.getenv("AUTH_API_LDAP_URL", "")
# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-cr'

TIME_ZONE = 'America/Costa_Rica'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Cuando creemos el Custom User, lo activamos
# AUTH_USER_MODEL = "usuarios.User"

LOGIN_URL = "/usuarios/login/"
LOGIN_REDIRECT_URL = "/dashboard/"
LOGOUT_REDIRECT_URL = "/usuarios/login/"

# Auth LDAP
AUTH_API_LDAP_URL = os.environ.get("AUTH_API_LDAP_URL", "")

# Seguridad de sesiones
SESSION_COOKIE_HTTPONLY = True      # JS no puede leer la cookie
SESSION_COOKIE_SAMESITE = "Lax"     # Protección CSRF básica
SESSION_COOKIE_AGE = 360 * 60       # 6 horas (igual que C# SessionTimeout=360)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True   # Renueva timeout con cada request
# Sesiones en base de datos (requerido para detección de duplicados real)
SESSION_ENGINE = "django.contrib.sessions.backends.db"
# CSRF
CSRF_COOKIE_HTTPONLY = False        # Django lo necesita en JS


# SESSION_COOKIE_SECURE = True        # Solo HTTPS (en producción)
# CSRF_COOKIE_SECURE = True           # Solo HTTPS


AUTHENTICATION_BACKENDS = [
    "apps.usuarios.backends.LDAPAuthBackend",
    "django.contrib.auth.backends.ModelBackend",
]


DATABASE_ROUTERS = ['apps.dashboard.routers.EncuestasDBRouter']