# Generated by Django 6.0.3 on 2026-03-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DashboardAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("view_dashboard", "Puede acceder al dashboard"),
                    ("view_encuestas", "Puede ver módulo Encuestas"),
                    ("view_formularios", "Puede ver módulo Formularios"),
                    ("view_encuesta_satisfaccion", "Encuesta de satisfacción"),
                    (
                        "view_encuesta_satisfaccion_oficina",
                        "Encuesta satisfacción Oficina Digital",
                    ),
                    ("view_encuesta_experiencia_web", "Experiencia en página web"),
                    (
                        "view_encuesta_satisfaccion_whatsapp_agente",
                        "Encuesta satisfacción WhatsApp Agente",
                    ),
                    (
                        "view_encuesta_satisfaccion_whatsapp",
                        "Encuesta satisfacción WhatsApp",
                    ),
                    (
                        "view_encuesta_feria_salud",
                        "Encuesta satisfacción Feria de la Salud",
                    ),
                    ("view_formulario_tarjetas", "Formularios: Tarjetas"),
                    ("view_formulario_ahorros", "Formularios: Ahorros"),
                    ("view_formulario_vivienda", "Formularios: Vivienda"),
                    ("view_formulario_prestamos", "Formularios: Préstamos"),
                    (
                        "view_formulario_control_credito",
                        "Formularios: Control de Crédito",
                    ),
                    (
                        "view_formulario_servicio_accionista",
                        "Formularios: Servicio al Accionista",
                    ),
                    ("view_formulario_seguros", "Formularios: Seguros"),
                ],
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
