# Generated by Django 6.0.3 on 2026-04-15 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DashboardAccess",
        ),
    ]
