# Generated by Django 6.0.3 on 2026-04-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dashboard", "0002_delete_dashboardaccess"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("view_dashboard", "Puede acceder al dashboard"),
                    ("view_encuestas", "Puede ver módulo Encuestas"),
                    ("view_formularios", "Puede ver módulo Formularios"),
                    ("view_encuesta_satisfaccion", "Encuesta: Satisfacción"),
                    (
                        "view_encuesta_satisfaccion_oficina",
                        "Encuesta: Satisfacción Oficina Digital",
                    ),
                    (
                        "view_encuesta_experiencia_web",
                        "Encuesta: Experiencia en página web",
                    ),
                    (
                        "view_encuesta_satisfaccion_whatsapp_agente",
                        "Encuesta: Satisfacción WhatsApp Agente",
                    ),
                    (
                        "view_encuesta_satisfaccion_whatsapp",
                        "Encuesta: Satisfacción WhatsApp",
                    ),
                    ("view_encuesta_feria_salud", "Encuesta: Feria de la Salud"),
                    ("view_formulario_tarjetas", "Formularios: Tarjetas (categoría)"),
                    (
                        "view_soli_tarj_credito",
                        "Tarjetas: Solicitud gestión tarjeta de crédito",
                    ),
                    (
                        "view_soli_tarj_debito",
                        "Tarjetas: Solicitud tarjeta Ciudadano de Oro",
                    ),
                    (
                        "view_soli_tarj_debito_gestion",
                        "Tarjetas: Solicitud gestión tarjeta de débito",
                    ),
                    (
                        "view_soli_redencion_puntos",
                        "Tarjetas: Solicitud redención de puntos",
                    ),
                    ("view_caja_ande_asistencia", "Tarjetas: Caja de ANDE Asistencia"),
                    ("view_formulario_ahorros", "Formularios: Ahorros (categoría)"),
                    (
                        "view_soli_deposito_salario",
                        "Ahorros: Solicitud depósito de salario",
                    ),
                    ("view_soli_ahorro_mod_cuota", "Ahorros: Modificación de cuota"),
                    (
                        "view_soli_reinversion_ahorro",
                        "Ahorros: Reinversión ahorro existente",
                    ),
                    (
                        "view_soli_autorizacion_ahorro_nuevo",
                        "Ahorros: Autorización ahorro nuevo",
                    ),
                    ("view_formulario_vivienda", "Formularios: Vivienda (categoría)"),
                    (
                        "view_soli_compra_vehiculo",
                        "Vivienda: Solicitud compra de vehículo",
                    ),
                    ("view_soli_prestamo_vivienda", "Vivienda: Préstamo para vivienda"),
                    (
                        "view_soli_prestamo_desarrollo",
                        "Vivienda: Préstamo desarrollo económico",
                    ),
                    ("view_formulario_prestamos", "Formularios: Préstamos (categoría)"),
                    (
                        "view_soli_presolicitud_credito",
                        "Préstamos: Pre-solicitud crédito personal",
                    ),
                    (
                        "view_formulario_control_credito",
                        "Formularios: Control de Crédito (categoría)",
                    ),
                    (
                        "view_comprobante_autorizacion_ahorro",
                        "Control Crédito: Comprobante autorización ahorro",
                    ),
                    (
                        "view_comprobantes_pago",
                        "Control Crédito: Comprobantes pago depósitos",
                    ),
                    (
                        "view_formulario_servicio_accionista",
                        "Formularios: Servicio al Accionista (categoría)",
                    ),
                    (
                        "view_soli_clave_cajatel",
                        "Servicio Accionista: Solicitud clave CajaTel",
                    ),
                    ("view_formulario_seguros", "Formularios: Seguros (categoría)"),
                    ("view_soli_seguro_viajero", "Seguros: Seguro viajero"),
                    ("view_soli_marchamo", "Seguros: Seguro marchamo"),
                ],
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
