# Generated by Django 6.0.3 on 2026-04-17 15:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_alter_dashboardaccess_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_index=True, max_length=150, verbose_name="Nombre de usuario"
                    ),
                ),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("LOGIN_OK", "Inicio de sesión exitoso"),
                            ("LOGIN_FAIL", "Intento de acceso fallido"),
                            ("LOGOUT", "Cierre de sesión"),
                            ("AGENTE_CREATE", "Agente creado"),
                            ("AGENTE_UPDATE", "Agente editado"),
                            ("AGENTE_DELETE", "Agente eliminado"),
                            ("AGENTE_RESTORE", "Agente restaurado"),
                            ("VIEW_REPORTE", "Acceso a reporte"),
                            ("VIEW_FORMULARIO", "Acceso a formulario"),
                            ("EXPORT_EXCEL", "Exportación Excel"),
                            ("EXPORT_QR", "Descarga QR"),
                            ("EXPORT_ZIP", "Descarga ZIP QR"),
                            ("PERMISO_DENEGADO", "Acceso denegado por permisos"),
                        ],
                        db_index=True,
                        max_length=50,
                        verbose_name="Acción",
                    ),
                ),
                (
                    "modulo",
                    models.CharField(
                        choices=[
                            ("SISTEMA", "Sistema"),
                            ("AGENTES", "Gestión de Agentes"),
                            ("ENCUESTAS", "Encuestas"),
                            ("FORMULARIOS", "Formularios"),
                            ("USUARIOS", "Usuarios"),
                            ("QR", "Códigos QR"),
                        ],
                        db_index=True,
                        max_length=50,
                        verbose_name="Módulo",
                    ),
                ),
                (
                    "severidad",
                    models.CharField(
                        choices=[
                            ("INFO", "Informativo"),
                            ("WARNING", "Advertencia"),
                            ("CRITICAL", "Crítico"),
                        ],
                        db_index=True,
                        default="INFO",
                        max_length=10,
                        verbose_name="Severidad",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=500, verbose_name="Descripción"),
                ),
                (
                    "objeto_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="ID del objeto",
                    ),
                ),
                (
                    "objeto_nombre",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nombre del objeto",
                    ),
                ),
                (
                    "datos_anteriores",
                    models.TextField(
                        blank=True,
                        help_text="Estado del objeto ANTES del cambio (JSON)",
                        null=True,
                        verbose_name="Datos anteriores",
                    ),
                ),
                (
                    "datos_nuevos",
                    models.TextField(
                        blank=True,
                        help_text="Estado del objeto DESPUÉS del cambio (JSON)",
                        null=True,
                        verbose_name="Datos nuevos",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Dirección IP",
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Navegador / Agente",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="URL accedida",
                    ),
                ),
                (
                    "metodo_http",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Método HTTP"
                    ),
                ),
                (
                    "fecha",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Fecha y hora",
                    ),
                ),
                (
                    "fecha_vencimiento",
                    models.DateTimeField(
                        db_index=True, editable=False, verbose_name="Vence el"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de auditoría",
                "verbose_name_plural": "Registros de auditoría",
                "ordering": ["-fecha"],
                "indexes": [
                    models.Index(
                        fields=["username", "fecha"], name="idx_audit_user_fecha"
                    ),
                    models.Index(
                        fields=["accion", "fecha"], name="idx_audit_accion_fecha"
                    ),
                    models.Index(
                        fields=["modulo", "fecha"], name="idx_audit_modulo_fecha"
                    ),
                    models.Index(
                        fields=["severidad", "fecha"], name="idx_audit_sev_fecha"
                    ),
                    models.Index(fields=["ip_address"], name="idx_audit_ip"),
                    models.Index(
                        fields=["fecha_vencimiento"], name="idx_audit_vencimiento"
                    ),
                ],
            },
        ),
    ]
