# Generated by Django 6.0.3 on 2026-04-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_alter_dashboardaccess_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetractorNotificado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("respuesta_id", models.IntegerField(unique=True)),
                ("encuesta_id", models.IntegerField(blank=True, null=True)),
                ("agente", models.CharField(blank=True, max_length=255)),
                ("sucursal", models.CharField(blank=True, max_length=255)),
                ("promedio", models.FloatField(null=True)),
                ("fecha_encuesta", models.DateTimeField(null=True)),
                ("fecha_notificado", models.DateTimeField(auto_now_add=True)),
                ("correo_enviado", models.BooleanField(default=True)),
                (
                    "error_envio",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
            ],
            options={
                "verbose_name": "Detractor notificado",
                "db_table": "dashboard_detractor_notificado",
            },
        ),
    ]
