# Generated by Django 6.0.3 on 2026-04-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_detractornotificado"),
    ]

    operations = [
        migrations.AddField(
            model_name="detractornotificado",
            name="grupo",
            field=models.CharField(
                choices=[
                    ("Satisfaccion", "Satisfacción"),
                    ("OficinaDigital", "Oficina Digital"),
                    ("PaginaWeb", "Página Web"),
                    ("WhatsAppAgente", "WhatsApp Agente"),
                    ("WhatsAppSinAgente", "WhatsApp Sin Agente"),
                ],
                db_index=True,
                default="Satisfaccion",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="detractornotificado",
            name="respuesta_id",
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name="detractornotificado",
            unique_together={("respuesta_id", "grupo")},
        ),
    ]
